# MkDocs configuration file
site_name: Ansible Best Practices
site_description: Best Practices and Style Guide for Ansible Projects
copyright: Copyright &copy; Computacenter 2023
edit_uri: ""
extra:
  social:
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.ccloud.ninja/tgruetzmacher/documentation-as-code
      name: Project in CCloud Gitlab
    - icon: fontawesome/brands/docker
      link: https://gitlab.ccloud.ninja/tgruetzmacher/documentation-as-code
      name: Docker Container in Github Container Repository
extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/tables.css
extra_javascript:
  - assets/javascripts/extra/refresh-on-toggle-dark-light.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - assets/javascripts/extra/tablesort.js
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - tables
  - toc:
      title: On this page
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - search:
      lang: en
      separator: '[\s]'
  - autolinks
  - git-revision-date-localized:
    # This plugin needs a Git executable and the .git folder
      enabled: !ENV [ENABLED_GIT_REVISION_DATE, True]
      fallback_to_build_date: true
      locale: en
  - print-site:
      add_cover_page: true
      add_print_site_banner: true
      cover_page_template: "docs/assets/pdf/cover-page.tpl"
      enabled: !ENV [ENABLED_PRINT_SITE, True]
      print_page_title: ""
      print_site_banner_template: "docs/assets/pdf/print-banner.tpl"
theme:
  name: material
  custom_dir: docs/assets/overrides
  icon:
    repo: fontawesome/brands/github
    admonition:
      example: octicons/terminal-24
  logo: assets/images/computacenter-logo-white.png
  language: en
  favicon: assets/images/computacenter-logo.png
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
  palette:
    - scheme: default
      primary: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
repo_url: https://github.com/TimGrt/Ansible-Best-Practices
repo_name: TimGrt/Ansible-Best-Practices
# Navigation definition
nav:
  - "Overview": index.md
  - "Mindset":
    - mindset/index.md
    - "The Zen of Ansible": mindset/zen.md
  - "Ansible":
    - ansible/index.md
    - "Installation": ansible/installation.md
    - "Project": ansible/project.md
    - "Inventory": ansible/inventory.md
    - "Variables": ansible/variables.md
    - "Playbook": ansible/playbook.md
    - "Roles": ansible/roles.md
    - "Tasks": ansible/tasks.md
  - "Ansible Development":
    - development/index.md
    - "Version Control": development/git.md
    - "Linting": development/linting.md
    - "Testing": development/testing.md
    - "Extending": development/extending.md
  - "Ansible Automation Platform":
    - automation-platform/index.md
    - "Credentials": automation-platform/credentials.md
    - "Workflows": automation-platform/workflows.md
