---
- name: Using no_log parameter
  hosts: database_servers
  tasks:
    - name: Add user
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ password }}"

    - name: Debugging a vaulted variable with no_log
      ansible.builtin.debug:
        msg: "{{ password }}"
      no_log: true
