- name: Upgrade all packages, excluding kernel & foo related packages # noqa package-latest
  ansible.builtin.yum:
    name: "*"
    state: latest
    exclude: kernel*,foo*
  when: upgrade_allowed | bool
